title: showcount
email: hw.robbins@gmail.com
description: >-
  Concert attendance tracking and sharing.
baseurl: ""
url: "https://showcount.com"

header_pages:
  - about.md
  - updates.md

collections:
  updates:
    output: true

theme: minima
plugins:
  - jekyll-feed
